import type {
  AgentIdentity,
  Product,
  OpenTab,
  Transaction,
  LedgerEvent,
  GrowthOpportunity,
  Policy,
  MerchantProfile,
  TxnStage,
} from './types';

export const demoMerchant: MerchantProfile = {
  businessName: 'Northwind Commerce',
  industry: 'Electronics & Accessories',
  storeUrl: 'northwind.example.com',
  contactEmail: 'owner@northwind.example.com',
  aiReadiness: 87,
  onboardingComplete: true,
  boundaries: {
    maxDiscount: 15,
    minMargin: 12,
    autoApproveThreshold: 5000,
    maxTxnAmount: 25000,
  },
};

export const demoAgents: AgentIdentity[] = [
  {
    id: 'agent_001',
    name: 'AI Shopping Assistant',
    organization: 'Aurora AI',
    provider: 'aurora-agent-platform',
    trustLevel: 'verified',
    authStatus: 'authenticated',
    permissionLevel: 'full',
    status: 'active',
    lastActivity: '2 minutes ago',
    avatarColor: 'from-electric-500 to-accent-500',
    activity: [
      { time: '10:05 AM', action: 'Transaction approved', detail: 'AeroBook Pro — ₹1,12,000' },
      { time: '10:03 AM', action: 'Policy check passed', detail: 'Within scope and authorization' },
      { time: '10:02 AM', action: 'Catalog discovered', detail: 'Electronics category' },
      { time: '09:48 AM', action: 'OpenTab activated', detail: '₹15,000 cap · Electronics' },
    ],
  },
  {
    id: 'agent_002',
    name: 'Buyer Agent',
    organization: 'Helix Commerce',
    provider: 'helix-buyer-os',
    trustLevel: 'verified',
    authStatus: 'authenticated',
    permissionLevel: 'full',
    status: 'active',
    lastActivity: '18 minutes ago',
    avatarColor: 'from-success-500 to-accent-500',
    activity: [
      { time: '09:51 AM', action: 'Transaction approved', detail: 'Desk Lamp — ₹2,400' },
      { time: '09:50 AM', action: 'Product compared', detail: 'Office accessories (3 items)' },
      { time: '09:49 AM', action: 'Catalog discovered', detail: 'Accessories category' },
    ],
  },
  {
    id: 'agent_003',
    name: 'Research Agent',
    organization: 'Independent',
    provider: 'open-research-bot',
    trustLevel: 'unknown',
    authStatus: 'unauthenticated',
    permissionLevel: 'public',
    status: 'active',
    lastActivity: '1 hour ago',
    avatarColor: 'from-warning-500 to-danger-500',
    activity: [
      { time: '09:12 AM', action: 'Public catalog viewed', detail: 'Gaming headset query' },
      { time: '09:10 AM', action: 'Restricted', detail: 'No transaction authority — public info only' },
    ],
  },
  {
    id: 'agent_004',
    name: 'Procurement Agent',
    organization: 'Meridian Labs',
    provider: 'meridian-procurement',
    trustLevel: 'known',
    authStatus: 'authenticated',
    permissionLevel: 'limited',
    status: 'paused',
    lastActivity: '3 hours ago',
    avatarColor: 'from-warning-500 to-electric-500',
    activity: [
      { time: '07:30 AM', action: 'Paused by merchant', detail: 'Unusual request volume detected' },
      { time: '07:15 AM', action: 'Rate limit triggered', detail: '12 requests in 60 seconds' },
      { time: '06:50 AM', action: 'Transaction escalated', detail: 'Bulk order exceeded auto-approval' },
    ],
  },
];

export const demoProducts: Product[] = [
  {
    id: 'p1',
    name: 'AeroBook Pro',
    category: 'Electronics',
    price: 112000,
    inventory: 24,
    image: 'laptop',
    aiReadiness: 94,
    readinessIssues: [],
    description: '14-inch ultralight laptop with 22-hour battery, M3 processor, 16GB RAM.',
    shipping: 'Ships in 1–2 business days. Free shipping over ₹5,000.',
    returns: '15-day return window. No questions asked.',
  },
  {
    id: 'p2',
    name: 'AeroBook Air',
    category: 'Electronics',
    price: 78000,
    inventory: 41,
    image: 'laptop',
    aiReadiness: 91,
    readinessIssues: [],
    description: '13-inch ultraportable, 18-hour battery, M2 processor, 8GB RAM.',
    shipping: 'Ships in 1–2 business days.',
    returns: '15-day return window.',
  },
  {
    id: 'p3',
    name: 'Wireless Mouse Pro',
    category: 'Accessories',
    price: 3200,
    inventory: 156,
    image: 'mouse',
    aiReadiness: 88,
    readinessIssues: [],
    description: 'Ergonomic wireless mouse with adaptive scroll and 6-month battery.',
    shipping: 'Same-day dispatch for orders before 2 PM.',
    returns: '15-day return window.',
  },
  {
    id: 'p4',
    name: 'Laptop Sleeve',
    category: 'Accessories',
    price: 1800,
    inventory: 88,
    image: 'sleeve',
    aiReadiness: 72,
    readinessIssues: ['AI systems may not be able to determine delivery time for this product.'],
    description: 'Felt laptop sleeve, fits 13–14 inch laptops.',
    shipping: 'Ships in 3–5 business days.',
    returns: '15-day return window.',
  },
  {
    id: 'p5',
    name: 'Desk Lamp',
    category: 'Accessories',
    price: 2400,
    inventory: 63,
    image: 'lamp',
    aiReadiness: 85,
    readinessIssues: [],
    description: 'LED desk lamp with wireless charging base and 3 color temperatures.',
    shipping: 'Same-day dispatch for orders before 2 PM.',
    returns: '15-day return window.',
  },
  {
    id: 'p6',
    name: 'USB-C Hub',
    category: 'Accessories',
    price: 4500,
    inventory: 0,
    image: 'hub',
    aiReadiness: 68,
    readinessIssues: ['Out of stock — AI cannot determine availability.', 'No estimated restock date provided.'],
    description: '8-in-1 USB-C hub with HDMI, SD, and 100W passthrough charging.',
    shipping: 'Ships in 1–2 business days.',
    returns: '15-day return window.',
  },
  {
    id: 'p7',
    name: 'Noise-Cancelling Headphones',
    category: 'Electronics',
    price: 18900,
    inventory: 32,
    image: 'headphones',
    aiReadiness: 90,
    readinessIssues: [],
    description: 'Over-ear ANC headphones, 40-hour battery, adaptive transparency.',
    shipping: 'Ships in 1–2 business days.',
    returns: '15-day return window.',
  },
  {
    id: 'p8',
    name: 'Mechanical Keyboard',
    category: 'Accessories',
    price: 6900,
    inventory: 27,
    image: 'keyboard',
    aiReadiness: 79,
    readinessIssues: ['Return policy details are missing for this product.'],
    description: '75% mechanical keyboard, hot-swappable switches, PBT keycaps.',
    shipping: 'Ships in 2–3 business days.',
    returns: 'Not specified.',
  },
];

export const demoOpenTabs: OpenTab[] = [
  {
    id: 'tab_001',
    agentId: 'agent_001',
    agentName: 'AI Shopping Assistant',
    trustLevel: 'verified',
    scope: ['Electronics', 'Accessories'],
    cap: 15000,
    remaining: 8500,
    autoApproveCeiling: 5000,
    expiresAt: 'Today, 6:00 PM',
    status: 'active',
    createdAt: 'Today, 9:48 AM',
  },
  {
    id: 'tab_002',
    agentId: 'agent_002',
    agentName: 'Buyer Agent',
    trustLevel: 'verified',
    scope: ['Accessories'],
    cap: 8000,
    remaining: 5600,
    autoApproveCeiling: 3000,
    expiresAt: 'Today, 8:00 PM',
    status: 'active',
    createdAt: 'Today, 9:30 AM',
  },
  {
    id: 'tab_003',
    agentId: 'agent_004',
    agentName: 'Procurement Agent',
    trustLevel: 'known',
    scope: ['Electronics'],
    cap: 20000,
    remaining: 0,
    autoApproveCeiling: 0,
    expiresAt: 'Expired',
    status: 'paused',
    createdAt: 'Yesterday, 4:20 PM',
  },
];

const baseStages = (decision: 'approved' | 'declined' | 'escalated'): TxnStage[] => [
  { id: 's1', label: 'Agent Request', status: 'passed', timestamp: '10:03:12', detail: 'AI Shopping Assistant requested purchase' },
  { id: 's2', label: 'Identity Verification', status: 'passed', timestamp: '10:03:12', detail: 'Agent identity verified — Aurora AI' },
  { id: 's3', label: 'Catalog Validation', status: 'passed', timestamp: '10:03:13', detail: 'Products found in catalog' },
  { id: 's4', label: 'Policy Check', status: decision === 'declined' ? 'failed' : 'passed', timestamp: '10:03:13', detail: 'Merchant policies evaluated' },
  { id: 's5', label: 'OpenTab Validation', status: decision === 'declined' ? 'failed' : decision === 'escalated' ? 'skipped' : 'passed', timestamp: '10:03:14', detail: 'Authorization scope and remaining balance checked' },
  { id: 's6', label: 'Payment Initiated', status: decision === 'approved' ? 'passed' : 'skipped', timestamp: '10:03:15', detail: 'Handed to payment provider' },
  { id: 's7', label: 'Payment Confirmed', status: decision === 'approved' ? 'passed' : 'skipped', timestamp: '10:04:02', detail: 'Payment provider confirmed' },
];

export const demoTransactions: Transaction[] = [
  {
    id: 'txn_20260828_0042',
    agentId: 'agent_001',
    agentName: 'AI Shopping Assistant',
    trustLevel: 'verified',
    products: [{ name: 'AeroBook Pro', price: 112000 }, { name: 'Wireless Mouse Pro', price: 3200 }],
    amount: 115200,
    openTabId: 'tab_001',
    decision: 'approved',
    reason: 'All policy checks passed. Within OpenTab scope and authorization.',
    paymentStatus: 'confirmed',
    stages: baseStages('approved'),
    timestamp: '2026-08-28T10:04:02',
  },
  {
    id: 'txn_20260828_0041',
    agentId: 'agent_002',
    agentName: 'Buyer Agent',
    trustLevel: 'verified',
    products: [{ name: 'Desk Lamp', price: 2400 }],
    amount: 2400,
    openTabId: 'tab_002',
    decision: 'approved',
    reason: 'Within auto-approval ceiling. All policies satisfied.',
    paymentStatus: 'confirmed',
    stages: baseStages('approved'),
    timestamp: '2026-08-28T09:51:00',
  },
  {
    id: 'txn_20260828_0040',
    agentId: 'agent_004',
    agentName: 'Procurement Agent',
    trustLevel: 'known',
    products: [{ name: 'Noise-Cancelling Headphones', price: 18900 }, { name: 'USB-C Hub', price: 4500 }],
    amount: 23400,
    openTabId: 'tab_003',
    decision: 'escalated',
    reason: 'Transaction exceeds auto-approval ceiling. Human approval required.',
    paymentStatus: 'awaiting_approval',
    stages: baseStages('escalated'),
    timestamp: '2026-08-28T06:50:00',
  },
  {
    id: 'txn_20260828_0039',
    agentId: 'agent_003',
    agentName: 'Research Agent',
    trustLevel: 'unknown',
    products: [{ name: 'Noise-Cancelling Headphones', price: 18900 }],
    amount: 18900,
    decision: 'declined',
    reason: 'Agent identity not verified. No transaction authority granted. Restricted to public information only.',
    paymentStatus: 'failed',
    stages: [
      { id: 's1', label: 'Agent Request', status: 'passed', timestamp: '09:12:00', detail: 'Research Agent requested purchase' },
      { id: 's2', label: 'Identity Verification', status: 'failed', timestamp: '09:12:00', detail: 'Agent identity not verified' },
      { id: 's3', label: 'Catalog Validation', status: 'skipped' },
      { id: 's4', label: 'Policy Check', status: 'skipped' },
      { id: 's5', label: 'OpenTab Validation', status: 'skipped' },
      { id: 's6', label: 'Payment Initiated', status: 'skipped' },
      { id: 's7', label: 'Payment Confirmed', status: 'skipped' },
    ],
    timestamp: '2026-08-28T09:12:00',
  },
];

export const demoLedger: LedgerEvent[] = [
  { id: 'e1', time: '10:05 AM', what: 'Payment confirmed', why: 'Payment provider confirmed transaction', who: 'system', whoType: 'system', transactionId: 'txn_20260828_0042' },
  { id: 'e2', time: '10:04 AM', what: 'Transaction approved', why: 'All policy checks passed', who: 'AI Shopping Assistant', whoType: 'agent', policy: 'auto-approval-under-5000', transactionId: 'txn_20260828_0042', decision: 'approved' },
  { id: 'e3', time: '10:04 AM', what: 'Merchant policy satisfied', why: 'Within discount and margin boundaries', who: 'system', whoType: 'system', policy: 'financial-boundaries' },
  { id: 'e4', time: '10:03 AM', what: 'Spending limit validated', why: 'Amount within remaining OpenTab authorization', who: 'system', whoType: 'system', policy: 'opentab-cap', transactionId: 'txn_20260828_0042' },
  { id: 'e5', time: '10:03 AM', what: 'OpenTab authority verified', why: 'Active OpenTab with valid scope', who: 'system', whoType: 'system', policy: 'opentab-scope', transactionId: 'txn_20260828_0042' },
  { id: 'e6', time: '10:03 AM', what: 'Agent requested AeroBook Pro', why: 'Verified agent initiated purchase', who: 'AI Shopping Assistant', whoType: 'agent', transactionId: 'txn_20260828_0042' },
  { id: 'e7', time: '10:02 AM', what: 'Verified AI agent discovered catalog', why: 'Agent browsed Electronics category', who: 'AI Shopping Assistant', whoType: 'agent' },
  { id: 'e8', time: '09:51 AM', what: 'Transaction approved', why: 'Within auto-approval ceiling', who: 'Buyer Agent', whoType: 'agent', policy: 'auto-approval-under-5000', transactionId: 'txn_20260828_0041', decision: 'approved' },
  { id: 'e9', time: '09:12 AM', what: 'Unknown agent restricted', why: 'Identity not verified — public info only', who: 'Research Agent', whoType: 'agent', policy: 'identity-required', decision: 'declined' },
  { id: 'e10', time: '07:30 AM', what: 'Agent paused by merchant', why: 'Unusual request volume detected', who: 'Procurement Agent', whoType: 'merchant', policy: 'rate-limit' },
  { id: 'e11', time: '07:15 AM', what: 'Rate limit triggered', why: '12 requests in 60 seconds exceeded threshold', who: 'Procurement Agent', whoType: 'system', policy: 'rate-limit' },
];

export const demoOpportunities: GrowthOpportunity[] = [
  {
    id: 'opp1',
    type: 'bundle',
    title: 'Laptop Sleeve + Wireless Mouse',
    description: 'Customers who purchase the AeroBook Pro frequently purchase these accessories. Bundling them increases average order value.',
    impact: 18400,
    confidence: 'high',
    risk: 'low',
    products: ['AeroBook Pro', 'Laptop Sleeve', 'Wireless Mouse Pro'],
    status: 'new',
  },
  {
    id: 'opp2',
    type: 'catalog',
    title: 'Fix delivery time on Laptop Sleeve',
    description: 'AI systems cannot determine delivery time for this product. Adding shipping estimates could improve AI-driven conversion.',
    impact: 6200,
    confidence: 'medium',
    risk: 'low',
    products: ['Laptop Sleeve'],
    status: 'new',
  },
  {
    id: 'opp3',
    type: 'pricing',
    title: 'Adjust Mechanical Keyboard price for margin',
    description: 'Current price is 8% below the optimal margin boundary. A small increase stays within your min-margin policy.',
    impact: 4100,
    confidence: 'medium',
    risk: 'medium',
    products: ['Mechanical Keyboard'],
    status: 'new',
  },
  {
    id: 'opp4',
    type: 'conversion',
    title: 'Restock USB-C Hub',
    description: 'High-demand product is out of stock with no restock date. Restocking recovers an estimated 22 lost AI-driven inquiries.',
    impact: 9800,
    confidence: 'high',
    risk: 'low',
    products: ['USB-C Hub'],
    status: 'new',
  },
];

export const demoPolicies: Policy[] = [
  { id: 'pol1', category: 'financial', name: 'Maximum Discount', description: 'No transaction may apply a discount greater than this percentage.', value: '15%', enabled: true },
  { id: 'pol2', category: 'financial', name: 'Minimum Margin', description: 'No product may be sold below this margin percentage.', value: '12%', enabled: true },
  { id: 'pol3', category: 'financial', name: 'Maximum Transaction Amount', description: 'No single transaction may exceed this amount.', value: '₹25,000', enabled: true },
  { id: 'pol4', category: 'agent', name: 'Allowed Categories', description: 'AI agents may only transact within these categories.', value: 'Electronics, Accessories', enabled: true },
  { id: 'pol5', category: 'agent', name: 'Maximum Requests per Minute', description: 'Rate limit applied to each agent.', value: '10 / min', enabled: true },
  { id: 'pol6', category: 'agent', name: 'Trusted Agents Only', description: 'Only verified agents may initiate transactions.', value: 'Verified + Known', enabled: true },
  { id: 'pol7', category: 'approval', name: 'Auto-Approval Ceiling', description: 'Transactions under this amount are auto-approved if all other checks pass.', value: '₹5,000', enabled: true },
  { id: 'pol8', category: 'approval', name: 'Human Approval Threshold', description: 'Transactions above this amount require human approval.', value: '₹25,000', enabled: true },
];

export const agentTrafficData = [
  { day: 'Mon', interactions: 18, conversions: 6 },
  { day: 'Tue', interactions: 24, conversions: 9 },
  { day: 'Wed', interactions: 31, conversions: 12 },
  { day: 'Thu', interactions: 28, conversions: 11 },
  { day: 'Fri', interactions: 42, conversions: 18 },
  { day: 'Sat', interactions: 35, conversions: 14 },
  { day: 'Sun', interactions: 22, conversions: 8 },
];

export const revenueData = [
  { month: 'Mar', revenue: 284000, agent: 12000 },
  { month: 'Apr', revenue: 312000, agent: 28000 },
  { month: 'May', revenue: 298000, agent: 41000 },
  { month: 'Jun', revenue: 356000, agent: 67000 },
  { month: 'Jul', revenue: 389000, agent: 94000 },
  { month: 'Aug', revenue: 421000, agent: 128000 },
];

export const agentTrafficTable = [
  { agent: 'AI Shopping Assistant', trust: 'verified' as const, intent: 'Laptop under ₹50K', product: 'AeroBook Pro', outcome: 'Purchased' },
  { agent: 'Buyer Agent', trust: 'verified' as const, intent: 'Office accessories', product: 'Desk Lamp', outcome: 'Approved' },
  { agent: 'Research Agent', trust: 'unknown' as const, intent: 'Gaming headset', product: '—', outcome: 'Public Info Only' },
  { agent: 'Procurement Agent', trust: 'known' as const, intent: 'Bulk electronics', product: 'USB-C Hub', outcome: 'Escalated' },
  { agent: 'AI Shopping Assistant', trust: 'verified' as const, intent: 'Wireless mouse', product: 'Wireless Mouse Pro', outcome: 'Purchased' },
  { agent: 'Buyer Agent', trust: 'verified' as const, intent: 'Keyboard under ₹8K', product: 'Mechanical Keyboard', outcome: 'Approved' },
];

export const aiAssistantSuggestions = [
  {
    id: 's1',
    query: 'How can I increase revenue this month?',
    response: 'I found 3 revenue opportunities in your catalog. The highest-impact one is bundling the Laptop Sleeve with the AeroBook Pro — customers who buy the laptop frequently buy these accessories. Estimated impact: +₹18,400/month with high confidence and low risk.',
    actions: [
      { label: 'Simulate Bundle', type: 'simulate' as const, opportunityId: 'opp1' },
      { label: 'Review Opportunity', type: 'review' as const, opportunityId: 'opp1' },
    ],
    confidence: 'high' as const,
    impact: '₹18,400/month',
  },
  {
    id: 's2',
    query: 'Why was the Procurement Agent paused?',
    response: 'The Procurement Agent was paused after triggering the rate-limit policy — it made 12 requests in 60 seconds, exceeding your 10/min threshold. Its last transaction was also escalated for human approval because it exceeded the auto-approval ceiling.',
    actions: [{ label: 'View Agent', type: 'review' as const, opportunityId: 'agent_004' }],
    confidence: 'high' as const,
    impact: '—',
  },
];
